###################################################################
#                 !!! DO NOT CHANGE THIS FILE !!!                 #
#              This file is managed by Terraform in               #
#          the broadinstitute/bibt-terraform repository.          #
#  Any changes made outside that repository WILL be overwritten.  #
###################################################################
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
